### PR TITLE
Milestone three

### PR DESCRIPTION
**Pull request by helciodev**
In this milestone, we have verified a friendship request cannot be duplicated and ensured the bidirectional friendship works well when a friendship status is confirmed.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @helciodev and @wandji20   ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [x]  I see you've created unit test cases with Rspec but let's also create integration test cases with Rspec and Capybara at least for the Friendship features (Send, Accept, and Reject a Friend Request and see user and friends post in the Timeline).

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @helciodev & @wandji20, 👋🏽 
 **Thank you for the good job you got going on. The app runs just fine and almost pass all test cases.**

## REQUIRED CHANGES

- [ ] when friendship is confirmed, an additional row with reversed user-friend pair should be created. The point of adding two rows per friendship is to avoid having to construct the list of friends with a double query as you do in the `all_friends` method in the user model. You need to also have another row for the pending friendships.  You can do something like this.
```
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships


# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

```

- [ ] There is some logic in the views folder (friendship_details.html.rb).  Remove the logic from the view files and transfer to te helpers method. View files are only meant to render pages to users and not perform any logic.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @helciodev & @wandji20, 👋🏽 
 **Thank you for the good job you got going on. The app runs just fine and almost pass all test cases.**

## REQUIRED CHANGES

- [x] when friendship is confirmed, an additional row with reversed user-friend pair should be created. The point of adding two rows per friendship is to avoid having to construct the list of friends with a double query as you do in the `all_friends` method in the user model. You need to also have another row for the pending friendships.  You can do something like this.
```
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships


# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

```

- [ ] There is some logic in the views folder (friendship_details.html.rb).  Remove the logic from the view files and transfer to te helpers folder. View files are only meant to render pages to users and not perform any logic.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- [ ] Good job, no logic in your view :+1: 
- [ ] When friendship is confirmed, an additional row with reversed user-friend pair is created :100: 

To Improve :factory_worker:

- [ ] There is a little bug in your users show page:

As you can see, I got error when I want to see user's profile. I am sure, you can fix it easily.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @wandji20  & @helciodev**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
